
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'E7B6B31D3F9129388A93BEFB65513AFA'
    
_lr_action_items = {'NAME':([0,4,5,7,8,9,],[2,11,11,11,11,11,]),'MINUS':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[4,-8,9,4,4,-7,4,4,4,-5,-8,9,9,-3,-4,-6,]),'LPAREN':([0,4,5,7,8,9,],[5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,8,9,],[6,6,6,6,6,6,]),'$end':([1,2,3,6,10,11,13,14,15,16,],[0,-8,-2,-7,-5,-8,-1,-3,-4,-6,]),'EQUALS':([2,],[7,]),'PLUS':([2,3,6,10,11,12,13,14,15,16,],[-8,8,-7,-5,-8,8,8,-3,-4,-6,]),'RPAREN':([6,10,11,12,14,15,16,],[-7,-5,-8,16,-3,-4,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,5,7,8,9,],[3,10,12,13,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME EQUALS expression','statement',3,'p_statement_assign','parser.py',61),
  ('statement -> expression','statement',1,'p_statement_expr','parser.py',65),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',69),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',70),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',75),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',79),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',83),
  ('expression -> NAME','expression',1,'p_expression_name','parser.py',87),
]
