* CCalc
  [[https://www.cs.utexas.edu/users/tag/cc/][The Causal Calculator]]
  [[http://www.cs.utexas.edu/users/tag/mad/][MAD]]
  [[https://www.cs.utexas.edu/users/tag/cc/tutorial/toc.html][Online Tutorial]].

** Running
   start swipl6 with ccal loaded:
   swipl6 -f path/to/ccalc.pl

** System Dependencies
   Needs swi-prolog < 7
   So rebuild from the git ref 406202420c of [[https://github.com/SWI-Prolog/swipl][swipl]]
   You need to update submodules first *before* going off HEAD.
   Make sure to add the compiler flags *brew info readline* suggests.

   Solvers need to be put in a *Darwin* solvers subdir.
   For Solvers, use [[https://github.com/roberto-bayardo/relsat][relsat]].
   [[https://gitlab.com/HenryKautz/Walksat][Walksat]] also compiles but doesn't output solutions.
   [[https://stackoverflow.com/questions/3987683][Homebrew install specific version]]
** Syntax
*** Constants
    Types:

    simpleFluent.
    inertialFluent.
    additiveFluent(type).

    sdFluent
    ? rigid

    action.
    exogenousAction.
    attribute of Action.
    additiveAction(type).
    ? abAction

    #+begin_src ccalc
    :- constants
    p :: inertialFluent(0..3);
    a :: exogenousAction.
    #+end_src

    #+RESULTS:

*** Transitions
    Define movements between states, using actions

    underlying language is "caused X if Y"

    constraint #1,#2 -> (constraint #1 ; constraint #2) ;
    constraint #1 -> caused false if -(#1);
    always #1,#2 -> (always #1 ; always #2) ;
    always #1 -> caused false after -(#1) ;  % or, constraint false after #1.
    default #1,#2 if #3 after #4 -> (default #1 if #3 after #4; default #2 if #3 after #4) ;
    default #1 if #2 after #3 -> caused #1 if #1 & #2 after #3 ;
    default #1,#2 after #3 -> (default #1 after #3 ; default #2 after #3) ;
    default #1 after #2 -> (default #1 if true after #2) ;
    default #1,#2 if #3 -> (default #1 if #3 ; default #2 if #3) ;
    default #1 if #2 -> caused #1 if #1 & #2 ;
    default #1,#2 -> default #1,#2 if true ;
    default #1 -> default #1 if true ;

    exogenous #1,#2 if #3 -> (exogenous #1 if #3 ; exogenous #2 if #3) ;
    exogenous #1 if #2 -> default #1 = var(sort(#1),-1) if #2 ;
    exogenous #1,#2 -> (exogenous #1 ; exogenous #2) ;
    exogenous #1 -> exogenous #1 if true .

    caused #1 after #3 -> caused #1 if true after #3 ;

    possibly caused #1 if #2 after #3 -> default #1 if #2 after #3 ;
    possibly caused #1 after #2 -> default #1 after #2;

    #1 causes #2 if #3 -> caused #2 after #1 & #3
    where action_formula(#1), simpleFluent_formula(#2) ;

    #1 causes #2 if #3 -> caused #2 if #1 & #3
    where action_formula(#1), action_formula(#2), fluent_formula(#3) ;

    #1 causes #2 -> #1 causes #2 if true
    where action_formula(#1);

    #1 may cause #2 if #3 -> default #2 after #3 & #4
    where tuple_to_conjunct(#1,#4) ;

    #1 may cause #2 -> default #2 after #3
    where tuple_to_conjunct(#1,#3) ;

    nonexecutable #1 if #2 -> always #2 ->> -(#3)
    where tuple_to_conjunct(#1,#3);

    nonexecutable #1 -> nonexecutable #1 if true;

    inertial #1,#2 if #3 -> (inertial #1 if #3 ; inertial #2 if #3) ;
    inertial #1 if #2 -> default #1 = var(sort(#1),-1)
    after #1 = var(sort(#1),-1) & #2 ;

    inertial #1,#2 -> (inertial #1 ; inertial #2) ;
    inertial #1 -> inertial #1 if true ;

    rigid #1,#2 -> (rigid #1 ; rigid #2) where is_constant(#1) ;
    rigid #1 -> caused false if -(#1 = var(sort(#1),-1))
    after #1 = var(sort(#1),-1) where is_constant(#1).




    #+begin_src prolog
    a causes c.
    a causes c=1 if c=0.
    nonexecutable a if c=3.
    #+end_src

*** Variables
    Uppercase as standard in prolog.
    #+begin_src prolog
    :- variables
    I :: 0..2.

    a causes c=I+1 if c=I.
    #+end_src

*** Macros

    #+begin_src prolog
    :- macros
    n -> 3.

    :- constants
    p :: inertialFluent(0..n).
    #+end_src

*** Queries
    Defined as paths of node -> action -> node of maxstep length.

    #+begin_src prolog
    %% Calls for finding paths of length 1.
    :- query
    maxstep :: 1.
    #+end_src

    Add requirements at particular nodes or edges.
    #+begin_src prolog
    :- query
    maxstep :: 2;
    0 : c=5; %% '& a'; or ', a;'
    0 : a;
    1 : a;
    maxstep :: 1.
    #+end_src

** Sandbox

   #+NAME: Non-Session Test
   #+begin_src ccalc :results output :query 1
     :- macros
        n -> 10.

     :- constants
        c :: inertialFluent(0..n);
        a ,
        b :: exogenousAction.

     :- variables
        I :: 0..n-1.

     a causes c=I+1 if c=I.
     b causes c=I+2 if c=I, I+2 < n.

     nonexecutable a if c >= n.
     nonexecutable b if c >= n-2.

     :- query          % prediction
        label :: 1;
        maxstep :: 2;
        0: c=5;
        0: a;
        1: a.

     :- query          % postdiction
        label :: 2;
        maxstep :: 2;
        maxstep: c=5;
        0: a;
        1: a.

     :- query          % planning
        label :: 3;
        maxstep :: 0..infinity;
        0: c=4;
        maxstep: c=10.
   #+end_src

   #+RESULTS: Non-Session Test
   #+begin_example
   FALLBACK: 0



   Causal Calculator: Version 2.0.
   Type 'help.' for online help.


   % loading file /Users/jgrey/github/otherlibs/ccalc/macros.std
   % loading file /var/folders/9k/kt7tw9c53zq0mgj4rwyd6cqc0000gn/T/babel-8N3Xln/ccalc-d1DO1o.pl
   % in transition mode...
   % 24 atoms, 48 rules, 149 clauses (28 new atoms)
   % Grounding time: 0.02 seconds
   % Completion time: 0.00 seconds
   % Total time: 0.02 seconds
   % Shifting atoms and clauses... done. (0.00 seconds)
   % After shifting: 83 atoms (including new atoms), 257 clauses
   % Writing input clauses... done.  (0.00 seconds)
   % Calling relsat 2.0... done.
   % Reading output file(s) from SAT solver... done.
   % Solution time: 0 seconds (prep 0 seconds, search 0 seconds)

   0:  c=5

   ACTIONS:  a

   1:  c=6

   ACTIONS:  a

   2:  c=7


   #+end_example






** Sandbox Session
   #+begin_src ccalc :results output :session test :as-file
     :- macros
        n -> 10.

     :- constants
        c :: inertialFluent(0..n);
        a ,
        b :: exogenousAction.

     :- variables
        I :: 0..n-1.


     a causes c=I+1 if c=I.
     b causes c=I+2 if c=I, I+2 < n.

     nonexecutable a if c >= n.
     nonexecutable b if c >= n-2.

     :- query          % prediction
        label :: 1;
        maxstep :: 2;
        0: c=5;
        0: a;
        1: a.

     :- query          % postdiction
        label :: 2;
        maxstep :: 2;
        maxstep: c=5;
        0: a;
        1: a.

     :- query          % planning
        label :: 3;
        maxstep :: 0..infinity;
        0: c=4;
        maxstep: c=10.
   #+end_src

   #+begin_src ccalc :results value :session test
   loadf coins.
   #+end_src

   #+begin_src ccalc :results output :session test
   query 2.
   #+end_src

   #+begin_src ccalc :results output :session mytest :as-file
   noconcurrency.

   :- constants
   a :: exogenousAction;
   b :: exogenousAction;
   q :: action;
   c, d, e :: inertialFluent.

   a causes c.
   caused d if c.
   b causes -d, -c.
   caused q if d.
   q causes e.
   %% caused a if d.

   nonexecutable a if c.
   nonexecutable b if -c.

   :- query
   label :: 1;
   maxstep :: 4;
   0: a, -d, -c;
   2: b.

   #+end_src

   #+begin_src ccalc :results output :session mytest
   query 1.
   #+end_src

   #+begin_src ccalc :results output :session mytest :as-file
   :- sorts
    blah.

    :- objects
    h :: blah;
    k :: blah.

    :- variables
    I :: 1..5;
    J :: blah;
    N :: 0..3.


    :- constants
    a :: inertialFluent;
    c :: exogenousAction;
    d :: inertialFluent.
    %% b :: inertialFluent(blah);
    %% d :: sdFluent;
    %% e :: boolean;
    %% f :: action;
    %% g :: exogenousAction;
    %% h :: attribute of g;
    %% i :: additiveAction(integer).

    %% default -a.
    %% default b.
    %% default b=h.
    %% default a=0.

    %% nonexecutable c(J) if a(J)=5.
    c causes d.


    :- query
    label :: 1;
    maxstep :: 2.

   #+end_src

   #+begin_src ccalc :results output :session mytest
   query 1.
   #+end_src

   #+begin_src ccalc :results output :session mytest
   show_rules.
   show_clauses.
   #+end_src


** Zoo
   [[https://www.cs.utexas.edu/users/tag/cc/examples/][Examples Source]]

   Giunchiglia et al:
   [[file:monkeys::%25%20Monkey%20and%20Bananas%20("Nonmonotonic%20Causal%20Theories,"%20Figures%2010-12)][Monkeys]]
   [[file:prediction][Prediction and Postdiction]]
   [[file:defeasible_rules][Defeasible Rules]]
   [[file:turkeys][Shooting Turkey]]
   [[file:work][Going to Work]]
   [[file:lifting][Lifing The Table]]
   [[file:pendulum][Pendulum]]
   [[file:publishing][Publishing]]

   Akman et al:
   [[file:zoo][Zoo]]
   [[~/github/languageLearning/ccalc/][Zoo Landscape]]
   [[file:animals][Zoo Animals]]
   [[file:movement][Zoo Movement]]
   [[file:actions][Zoo Actions]]
   [[file:little_zoo][Little Zoo]]

   [[file:traffic][Traffic]]

   Lifschitz et al:
   [[file:airport-domain][Airport Domain]]
   [[file:airport-problem][Airport Problem]]

   Lee and Lifschitz:
   [[file:spacecraft][Spacecraft Domain]]
   [[file:spacecraft-test][Spacecraft Example]]
   [[file:buying][Buying and Selling Domain]]
   [[file:buying-test][Buying Example]]
   [[file:mcp][Missionaries and Cannibals]]
   [[file:mcp-test][Missionaries and Cannibals Test]]

   Other:
   [[file:hanoi][Hanoi]]
   [[file:bw][Blocks World Description]]
   [[file:bw-test][Blocks World Problem]]
