
all:
	python -m unittest EL*.py -v -f


parser:
	python ELParser_tests.py -v -f

trie:
	python ELTrie_tests.py -v -f

parser2trie:
	python ELParser_to_Trie_tests.py -v -f

runtime:
	python ELRuntime_tests.py -v -f

clean:
	-rm *.log
