* [[https://tidalcycles.org/][Tidal Cycles]]
  Haskell based pattern language.
** Startup and setup
   cabal install tidal
   supercollider install SuperDirt quark
   sounds are in ~/Library/Application Support/Supercollider/downloaded-quarks
   Tidal mode for haskell, sclang mode for supercollider
   Make sure to have the SuperDirt quark in the search paths of the yaml config for sc.
   Start Supercollider with sclang-start, then run SuperDirt.Start
   Start tidal with C-c C-s, 
   Run lines of tidal with C-c C-c
** Simple sounds
   d1 $ sound "bd"
   d1 silence

** Concepts
   d1 - d9 voices.

   sound : create a pattern of sound samples
   "bd" - pattern of a single bass drum

   "bd:3" - select the third sample from the bd pattern
   "bd" # n "3" - alternative version of sample select

   hush - silence everything

   "[a b c]" - group within a subdivision. Still sequential. can be nested
   
   "<a b c>" - only play one each cycle

   "a*2" - repeat 2 times. Functionally: "a a"
   "a/2" - half as many times. 

   rev - reverse a pattern
   every n func pattern - apply the func to the pattern every n times
   
   fast n, slow n - slow by the amount. slow 0.25 == fast 4

   a # b - apply b to pattern a
   
   a # crush "4" - apply the crush effect to a
   
   Effects include: crush, speed, delay,
   gain - range 0 to 1
   pan - range 0 to 1
   shape - range 0 to 1
   vowel - a e i o u
   n = the sample number
   off

   |=| applies patterns
   |*| multiplies them

   
